---
- hosts: localhost
  tasks:

########################################
# Install some packages I do like
########################################
  - name: update apt cache
    apt:
      update_cache: yes
    become: true
  - name: install emacs25
    apt:
      name: emacs25
    become: true
  - name: install dvipng
    apt:
      name: dvipng
    become: true
  - name: install clojure
    apt:
      name: clojure
    become: true
  - name: install virtualenvwrapper
    apt:
      name: virtualenvwrapper
    become: true
  - name: install ack
    apt:
      name: ack
    become: true
  - name: install terminator
    apt:
      name: terminator
    become: true
  - name: install byobu
    apt:
      name: byobu
    become: true
  - name: install dstat
    apt:
      name: dstat
    become: true

########################################
# Just a bunch of git repositories
########################################
#  - name: clone git repository cudos/dotfiles
#    git:
#      repo: git@github.com:cudos/dotfiles.git
#      version: master
#      dest: ~/git/cudos/dotfiles
  - name: clone git repository cudos/pe-clojure
    git:
      repo: git@github.com:cudos/pe-clojure.git
      version: master
      dest: ~/git/cudos/pe-clojure
  - name: clone git repository cudos/readme
    git:
      repo: git@github.com:cudos/readme.git
      version: master
      dest: ~/git/cudos/readme
  - name: clone git repository cudos/emacs.d
    git:
      repo: git@github.com:cudos/emacs.d.git
      version: master
      dest: ~/git/cudos/emacs.d
  - name: clone git repository cudos/trender
    git:
      repo: git@github.com:cudos/trender.git
      version: master
      dest: ~/git/cudos/trender
  - name: clone git repository clojure/clojure
    git:
      repo: https://github.com/clojure/clojure.git
      version: master
      dest: ~/git/clojure
  - name: clone git repository technomancy/leiningen
    git:
      repo: https://github.com/technomancy/leiningen.git
      version: stable
      dest: ~/git/leiningen
  - name: clone git repository quantopian/zipline
    git:
      repo: https://github.com/quantopian/zipline.git
      version: master
      dest: ~/git/zipline
########################################
# Just a bunch of symbolic links
########################################
  - name: remove eventually existing ~/.emacs.d
    file:
      path: ~/.emacs.d
      state: absent
  - name: set symbolic link ~/git/cudos/emacs.d/bookmarks
    file:
      src: ~/Dropbox/emacs-bookmarks
      dest: ~/git/cudos/emacs.d/bookmarks
      state: link
  - name: set symbolic link ~/git/cudos/emacs.d/projectile-bookmarks.eld
    file:
      src: ~/Dropbox/emacs-projectile-bookmarks.eld
      dest: ~/git/cudos/emacs.d/projectile-bookmarks.eld
      state: link
  - name: set symbolic link ~/.emacs.d
    file:
      src: ~/git/cudos/emacs.d
      dest: ~/.emacs.d
      state: link
  - name: set symbolic link ~/org
    file:
      src: ~/Dropbox/org
      dest: ~/org
      state: link
  - name: remove eventually existing ~/.bashrc
    file:
      path: ~/.bashrc
      state: absent
  - name: set symbolic link ~/.bashrc
    file:
      src: ~/git/cudos/dotfiles/.bashrc
      dest: ~/.bashrc
      state: link
  - name: remove eventually existing ~/.config/terminator/config
    file:
      path: ~/.config/terminator/config
      state: absent
  - name: set symbolic link ~/.config/terminator/config
    file:
      src: ~/git/cudos/dotfiles/terminator-config
      dest: ~/.config/terminator/config
      state: link
  - name: copy lein script
    shell: cp ~/git/leiningen/bin/lein ~/bin/
    args:
      creates: ~/bin/lein
  - name: initially run lein
    shell: ~/bin/lein
    args:
      creates: ~/.lein
  - name: set symbolic link ~/Briefe
    file:
      src: ~/Dropbox/Briefe
      dest: ~/Brriefe
      state: link

########################################
# Install fzf
########################################
  - name: clone git repository junegunn/fzf
    git:
      repo: https://github.com/junegunn/fzf.git
      version: master
      dest: ~/git/fzf
  - name: build fzf
    expect:
      command: /home/jens/git/fzf/install
      responses:
        'Do you want to enable fuzzy auto-completion\? \(\[y\]/n\)': "y"
        'Do you want to enable key bindings\? \(\[y\]/n\)': "y"
        'Do you want to update your shell configuration files\? \(\[y\]/n\)': "y"